float64[] next_state
float64 reward
float64[] state
float64[] action
bool done
float64 target_cost
float64 unilateral
float64 friction
float64 singularity
float64 joint_range
float64 joint_torques
float64 no_touchdown
float64 smoothness
float64 straight
---
float64 ack